### ISSUE TITLE
Estudar transferência para o docsify

### ISSUE THREAD

**Issue by heylisten64** [Requisitos2-2019/Yellow-Grupo-4#11]
Alguns amigos que já fizeram a matéria (eram do grupo do Habtica) recomendaram a utilização do Docsify no lugar do mkdocs por questão de estética e organização. Se formos fazer a transferência seria legal se fosse feita por agora já que não temos tantos conteúdos.

**Tarefas**
- [x] Verificar a documentação do Docsify se é simples criar a Page

**Critérios de aceitação**

- [x] Documentar o quão difícil é essa migração.
- [x] Caso seja simples, ao menos iniciar a migração para que esteja pronto no PC1.

**Comment by pedroeagle** [comment]
estou lendo a documentação do docsify e parece ser bem simples a inserção de conteúdos. segue o "início rápido":
https://docsify.js.org/#/quickstart?id=initialize

**Comment by pedroeagle** [comment]
criei uma versão da nossa page no docsify, está na branch issue_11. pra rodar tem que entrar no diretório docsify e dar:
```
docsify serve docs
```
porém ainda está sem tema algum, não consegui adicionar.

**Comment by pedroeagle** [comment]
Fiz a migração porém achei mais complicado a utilizar o mkdocs.
