### ISSUE TITLE
Fazer cronograma de planejamento do semestre

### ISSUE THREAD

**Issue by pedroeagle** [Requisitos2-2019/Yellow-Grupo-4#9]
Criar o planejamento de tudo o que será feito no semestre.

**Tarefas**

- [x] O cronograma deve ser criado. 

**Critérios de aceitação**

- [x] Cronograma desenvolvido no canva, ou outra plataforma similar.
- [x] Cronograma de acordo com o plano de estudos da disciplina.

**Comment by juniopereirab** [comment]
Fiz o seguinte planejamento: 
![Planejamento de Requisitos de Software](https://user-images.githubusercontent.com/17153869/63972228-a554d100-ca7e-11e9-9aaf-4f65890a19e1.jpg)

**Comment by pedroeagle** [comment]
> Fiz o seguinte planejamento:
> ![Planejamento de Requisitos de Software](https://user-images.githubusercontent.com/17153869/63972228-a554d100-ca7e-11e9-9aaf-4f65890a19e1.jpg)

seria possível deixar com fundo branco? só pra ficar melhor encaixado no gh pages msm

**Comment by juniopereirab** [comment]
Atualizei:
![Planejamento de Requisitos de Software](https://user-images.githubusercontent.com/17153869/63987062-17440f00-caad-11e9-8901-4c39550caad1.jpg)
